language: go

env: GO111MODULE=on

go: 
    - 1.13.4    

git:
    depth: 1

notifications:
    email: flase

branches:
    only:
        - master

script: go test -v -args -ip= ${AWS_RDS_DEMO} -user= ${MYUSER} -pass= ${MYPASS} -schema= sakila